### ISSUE TITLE
Margins for Seadragon viewer

### ISSUE THREAD

**Issue by apjanco** [HCDigitalScholarship/GAM#12]
Change all_documents template so that view has margins similar to clipboard template (document_multi).
Change this: 
http://192.241.128.56/en/Archivo%20del%20GAM/Desaparecidos/1/1/2/

To have margins like this: 
http://192.241.128.56/en/portapapeles/

**Comment by demery12** [comment]
fixed. The seadragon container was outside the container for the page.
