### ISSUE TITLE
Unable to edit carpetas in admin 

### ISSUE THREAD

**Issue by apjanco** [HCDigitalScholarship/GAM#53]
Error is __str__ returned non-string (type NoneType)

**Comment by iafisher** [comment]
When do you get the error? (when you open the carpetas panel, when you try to save a model, etc.)

**Comment by apjanco** [comment]
It was when you opened an individual folder for editing.  Turns out the NoneType was in a related model.  I removed a Null persona object and all works well.  This can be closed.
